setwd("E:/JKUAT/csv")
library(readr)
library(rpivotTable)
library(dplyr)
library(plyr)
library(tidyr)
library(dplyr)
TB_Combined <- read_csv("TB_Combined.csv")
View(TB_Combined)
#TB counts per health facility
tb_counts <- ddply(TB_Combined, .(TB_Combined$`Health Facility`), nrow)
names(tb_counts) <- c("Health Facility", "TB_Cases")
sum(tb_counts$TB_Cases)
View(tb_counts)
write.csv(tb_counts,"tb_counts.csv")
#HIV positive and negative
hiv_status<- table(TB_Combined$`Health Facility`,TB_Combined$`HIV Status`)
write.csv(hiv_status,"hiv_status.csv")
#female $ male seperate
sex<-table(TB_Combined$`Health Facility`,TB_Combined$`Sex M/F`)
View(sex)
write.csv(sex,"sex.csv")
sex<-read.csv("sex.csv")
view(sex)
#type of patient seperate
type_patient<-table(TB_Combined$`Health Facility`,TB_Combined$`Type of patient`)
write.csv(type_patient,"type_patient.csv")
type_patient<-read.csv("type_patient")
view(type_patient)